//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountryClubAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CountryClubEntities : DbContext
    {
        public CountryClubEntities()
            : base("name=CountryClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Post_has_Comment> Post_has_Comment { get; set; }
        public virtual DbSet<PostLikedbyUser> PostLikedbyUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Has_Interest> User_Has_Interest { get; set; }
    }
}
