//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountryClubAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_has_Comment
    {
        public int PostsComment_ID { get; set; }
        public Nullable<int> Post_ID { get; set; }
        public Nullable<int> Comment_ID { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Post Post { get; set; }
    }
}
